
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "labquiz"
version = "0.7.9.1"
description = "Quizzes intégrés pour Jupyter"
license = "GPL-3.0-or-later"
authors = [{ name="J.-F. Bercher", email="jf.bercher@esiee.fr" }]
dependencies = [
    "ipywidgets>=7.6.5",
    "pyyaml",
    "cryptography",
    "ipython",
    "numpy",
    "pandas",
    "requests",
] 
keywords = ["quizzes", "jupyter", "hash:825b19ef2c49a9d2483e7bc5a725947f92186534d85efe0180b6dcf4a73d2cdc"]
