[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "labquiz"
version = "0.8.5"
description = "Quizzes intégrés pour Jupyter"
license = { text = "GPL-3.0-or-later" }
authors = [
    { name = "J.-F. Bercher", email = "jf.bercher@esiee.fr" }
]
dependencies = [
    "ipywidgets>=7.6.5",
    "pyyaml",
    "cryptography",
    "ipython",
    "numpy",
    "pandas",
    "requests",
]
keywords = ["quizzes", "jupyter", "hash:f4e677cd85ef11836d4449a49822f2451bdda9c58d5e5af6d565fca29e706f8b"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"labquiz" = ["**/*.mo", "**/*.po"]
